// Map from wikiTitleName => prettyName.
// Run `npm run update-creatures` to get a list of missing entries based
// on the latest tibia-json data.
export const uglyToPrettyNames = new Map([
	['Abyssal Calamary', 'abyssal calamary'],
	['Acid Blob', 'acid blob'],
	['Acolyte of Darkness', 'acolyte of darkness'],
	['Acolyte of the Cult', 'acolyte of the cult'],
	['Adept of the Cult', 'adept of the cult'],
	['Adult Goanna', 'adult goanna'],
	['Adventurer', 'adventurer'],
	['Afflicted Strider', 'afflicted strider'],
	['Agrestic Chicken', 'agrestic chicken'],
	['Albino Dragon', 'albino dragon'],
	['Amazon', 'amazon'],
	['Ancient Scarab', 'ancient scarab'],
	['Angry Sugar Fairy', 'angry sugar fairy'],
	['Animated Feather', 'animated feather'],
	['Animated Snowman', 'animated snowman'],
	['Arachnophobica', 'arachnophobica'],
	['Arctic Faun', 'arctic faun'],
	['Armadile', 'armadile'],
	['Askarak Demon', 'askarak demon'],
	['Askarak Lord', 'askarak lord'],
	['Askarak Prince', 'askarak prince'],
	['Assassin', 'assassin'],
	['Azure Frog', 'azure frog'],
	['Badger', 'badger'],
	['Baleful Bunny', 'baleful bunny'],
	['Bandit', 'bandit'],
	['Bane Bringer', 'bane bringer'],
	['Bane of Light', 'bane of light'],
	['Banshee', 'banshee'],
	['Barbarian Bloodwalker', 'barbarian bloodwalker'],
	['Barbarian Brutetamer', 'barbarian brutetamer'],
	['Barbarian Headsplitter', 'barbarian headsplitter'],
	['Barbarian Skullhunter', 'barbarian skullhunter'],
	['Barkless Devotee', 'barkless devotee'],
	['Barkless Fanatic', 'barkless fanatic'],
	['Bashmu', 'bashmu'],
	['Bat', 'bat'],
	['Bear', 'bear'],
	['Behemoth', 'behemoth'],
	['Bellicose Orger', 'bellicose orger'],
	['Berrypest', 'berrypest'],
	['Berserker Chicken', 'berserker chicken'],
	['Betrayed Wraith', 'betrayed wraith'],
	['Biting Book', 'biting book'],
	['Black Sheep', 'black sheep'],
	['Black Sphinx Acolyte', 'black sphinx acolyte'],
	['Blemished Spawn', 'blemished spawn'],
	['Blightwalker', 'blightwalker'],
	['Bloated Man-Maggot', 'bloated man-maggot'],
	['Blood Beast', 'blood beast'],
	['Blood Crab', 'blood crab'],
	['Blood Hand', 'blood hand'],
	['Blood Priest', 'blood priest'],
	['Blue Djinn', 'blue djinn'],
	['Bluebeak', 'bluebeak'],
	['Boar Man', 'boar man'],
	['Boar', 'boar'],
	['Bog Frog', 'bog frog'],
	['Bog Raider', 'bog raider'],
	['Bonebeast', 'bonebeast'],
	['Bonelord', 'bonelord'],
	['Bony Sea Devil', 'bony sea devil'],
	['Boogy', 'boogy'],
	['Brachiodemon', 'brachiodemon'],
	['Brain Squid', 'brain squid'],
	['Braindeath', 'braindeath'],
	['Bramble Wyrmling', 'bramble wyrmling'],
	['Branchy Crawler', 'branchy crawler'],
	['Breach Brood', 'breach brood'],
	['Bride of Night', 'bride of night'],
	['Brimstone Bug', 'brimstone bug'],
	['Brinebrute Inferniarch', 'brinebrute inferniarch'],
	['Broken Shaper', 'broken shaper'],
	['Broodrider Inferniarch', 'broodrider inferniarch'],
	['Bug', 'bug'],
	['Bulltaur Alchemist', 'bulltaur alchemist'],
	['Bulltaur Brute', 'bulltaur brute'],
	['Bulltaur Forgepriest', 'bulltaur forgepriest'],
	['Burning Book', 'burning book'],
	['Burning Gladiator', 'burning gladiator'],
	['Burster Spectre', 'burster spectre'],
	['Butterfly (Blue)', 'butterfly (blue)'],
	['Butterfly (Purple)', 'butterfly (purple)'],
	['Butterfly (Red)', 'butterfly (red)'],
	['Cake Golem', 'cake golem'],
	['Calamary', 'calamary'],
	['Candy Floss Elemental', 'candy floss elemental'],
	['Candy Horror', 'candy horror'],
	['Capricious Phantom', 'capricious phantom'],
	['Carniphila', 'carniphila'],
	['Carnivostrich', 'carnivostrich'],
	['Carrion Worm', 'carrion worm'],
	['Cat', 'cat'],
	['Cave Chimera', 'cave chimera'],
	['Cave Devourer', 'cave devourer'],
	['Cave Parrot', 'cave parrot'],
	['Cave Rat', 'cave rat'],
	['Centipede', 'centipede'],
	['Chakoya Toolshaper', 'chakoya toolshaper'],
	['Chakoya Tribewarden', 'chakoya tribewarden'],
	['Chakoya Windcaller', 'chakoya windcaller'],
	['Chasm Spawn', 'chasm spawn'],
	['Chicken', 'chicken'],
	['Chocolate Blob', 'chocolate blob'],
	['Choking Fear', 'choking fear'],
	['Cinder Wyrmling', 'cinder wyrmling'],
	['Clay Guardian', 'clay guardian'],
	['Cliff Strider', 'cliff strider'],
	['Cloak of Terror', 'cloak of terror'],
	['Clomp', 'clomp'],
	['Cobra Assassin', 'cobra assassin'],
	['Cobra Scout', 'cobra scout'],
	['Cobra Vizier', 'cobra vizier'],
	['Cobra', 'cobra'],
	['Converter', 'converter'],
	['Coral Frog', 'coral frog'],
	['Corrupted Ghost', 'corrupted ghost'],
	['Corrupted Skeleton', 'corrupted skeleton'],
	['Corym Charlatan', 'corym charlatan'],
	['Corym Skirmisher', 'corym skirmisher'],
	['Corym Vanguard', 'corym vanguard'],
	['Courage Leech', 'courage leech'],
	['Cow', 'cow'],
	['Crab', 'crab'],
	['Crape Man', 'crape man'],
	['Crawler', 'crawler'],
	['Crazed Beggar', 'crazed beggar'],
	['Crazed Summer Rearguard', 'crazed summer rearguard'],
	['Crazed Summer Vanguard', 'crazed summer vanguard'],
	['Crazed Winter Rearguard', 'crazed winter rearguard'],
	['Crazed Winter Vanguard', 'crazed winter vanguard'],
	['Cream Blob', 'cream blob'],
	['Creepy Crawler', 'creepy crawler'],
	['Crimson Frog', 'crimson frog'],
	['Crocodile', 'crocodile'],
	['Crusader', 'crusader'],
	['Crustacea Gigantica', 'crustacea gigantica'],
	['Crypt Construct', 'crypt construct'],
	['Crypt Defiler', 'crypt defiler'],
	['Crypt Fiend', 'crypt fiend'],
	['Crypt Mage', 'crypt mage'],
	['Crypt Shambler', 'crypt shambler'],
	['Crypt Warden', 'crypt warden'],
	['Crypt Warrior', 'crypt warrior'],
	['Crystal Spider', 'crystal spider'],
	['Crystal Wolf', 'crystal wolf'],
	['Crystalcrusher', 'crystalcrusher'],
	['Cult Believer', 'cult believer'],
	['Cult Enforcer', 'cult enforcer'],
	['Cult Scholar', 'cult scholar'],
	['Cunning Werepanther', 'cunning werepanther'],
	['Cursed Ape', 'cursed ape'],
	['Cursed Book', 'cursed book'],
	['Cursed Prospector', 'cursed prospector'],
	['Cyclops Drone', 'cyclops drone'],
	['Cyclops Smith', 'cyclops smith'],
	['Cyclops', 'cyclops'],
	['Cyclursus', 'cyclursus'],
	['Damaged Crystal Golem', 'damaged crystal golem'],
	['Damaged Worker Golem', 'damaged worker golem'],
	['Dark Apprentice', 'dark apprentice'],
	['Dark Carnisylvan', 'dark carnisylvan'],
	['Dark Faun', 'dark faun'],
	['Dark Magician', 'dark magician'],
	['Dark Monk', 'dark monk'],
	['Dark Torturer', 'dark torturer'],
	['Darklight Construct', 'darklight construct'],
	['Darklight Emitter', 'darklight emitter'],
	['Darklight Matter', 'darklight matter'],
	['Darklight Source', 'darklight source'],
	['Darklight Striker', 'darklight striker'],
	['Dawnfire Asura', 'dawnfire asura'],
	['Death Blob', 'death blob'],
	['Death Priest', 'death priest'],
	['Deathling Scout', 'deathling scout'],
	['Deathling Spellsinger', 'deathling spellsinger'],
	['Deepling Brawler', 'deepling brawler'],
	['Deepling Elite', 'deepling elite'],
	['Deepling Guard', 'deepling guard'],
	['Deepling Master Librarian', 'deepling master librarian'],
	['Deepling Scout', 'deepling scout'],
	['Deepling Spellsinger', 'deepling spellsinger'],
	['Deepling Tyrant', 'deepling tyrant'],
	['Deepling Warrior', 'deepling warrior'],
	['Deepling Worker', 'deepling worker'],
	['Deepsea Blood Crab', 'deepsea blood crab'],
	['Deepworm', 'deepworm'],
	['Deer', 'deer'],
	['Defiler', 'defiler'],
	['Demon Outcast', 'demon outcast'],
	['Demon Parrot', 'demon parrot'],
	['Demon Skeleton', 'demon skeleton'],
	['Demon', 'demon'],
	['Destroyer', 'destroyer'],
	['Devoted Radiant Acolyte', 'devoted radiant acolyte'],
	['Devoted Radiant Inquisitor', 'devoted radiant inquisitor'],
	['Devoted Radiant Paragon', 'devoted radiant paragon'],
	['Devoted Radiant Templar', 'devoted radiant templar'],
	['Devoted Radiant Warden', 'devoted radiant warden'],
	['Devoted Radiant Zealot', 'devoted radiant zealot'],
	['Devourer', 'devourer'],
	['Diabolic Imp', 'diabolic imp'],
	['Diamond Servant Replica', 'diamond servant replica'],
	['Diamond Servant', 'diamond servant'],
	['Dire Penguin', 'dire penguin'],
	['Diremaw', 'diremaw'],
	['Distorted Phantom', 'distorted phantom'],
	['Dog', 'dog'],
	['Doom Deer', 'doom deer'],
	['Doomsday Cultist', 'doomsday cultist'],
	['Dragolisk', 'dragolisk'],
	['Dragon Hatchling', 'dragon hatchling'],
	['Dragon Lord Hatchling', 'dragon lord hatchling'],
	['Dragon Lord', 'dragon lord'],
	['Dragon', 'dragon'],
	['Dragonling', 'dragonling'],
	['Draken Abomination', 'draken abomination'],
	['Draken Elite', 'draken elite'],
	['Draken Spellweaver', 'draken spellweaver'],
	['Draken Warmaster', 'draken warmaster'],
	['Draptor', 'draptor'],
	['Dread Intruder', 'dread intruder'],
	['Drillworm', 'drillworm'],
	['Dromedary', 'dromedary'],
	['Dryad', 'dryad'],
	['Duskbringer', 'duskbringer'],
	['Dwarf Geomancer', 'dwarf geomancer'],
	['Dwarf Guard', 'dwarf guard'],
	['Dwarf Henchman', 'dwarf henchman'],
	['Dwarf Soldier', 'dwarf soldier'],
	['Dwarf', 'dwarf'],
	['Dworc Fleshhunter', 'dworc fleshhunter'],
	['Dworc Shadowstalker', 'dworc shadowstalker'],
	['Dworc Venomsniper', 'dworc venomsniper'],
	['Dworc Voodoomaster', 'dworc voodoomaster'],
	['Earth Elemental', 'earth elemental'],
	['Efreet', 'efreet'],
	['Elder Bonelord', 'elder bonelord'],
	['Elder Forest Fury', 'elder forest fury'],
	['Elder Mummy', 'elder mummy'],
	['Elder Wyrm', 'elder wyrm'],
	['Elephant', 'elephant'],
	['Elf Arcanist', 'elf arcanist'],
	['Elf Overseer', 'elf overseer'],
	['Elf Scout', 'elf scout'],
	['Elf', 'elf'],
	['Emerald Damselfly', 'emerald damselfly'],
	['Emerald Tortoise', 'emerald tortoise'],
	['Energetic Book', 'energetic book'],
	['Energuardian of Tales', 'energuardian of tales'],
	['Energy Elemental', 'energy elemental'],
	['Enfeebled Silencer', 'enfeebled silencer'],
	['Enlightened of the Cult', 'enlightened of the cult'],
	['Enraged Crystal Golem', 'enraged crystal golem'],
	['Enslaved Dwarf', 'enslaved dwarf'],
	['Eternal Guardian', 'eternal guardian'],
	['Evil Prospector', 'evil prospector'],
	['Evil Sheep Lord', 'evil sheep lord'],
	['Evil Sheep', 'evil sheep'],
	['Execowtioner', 'execowtioner'],
	['Exotic Bat', 'exotic bat'],
	['Exotic Cave Spider', 'exotic cave spider'],
	['Eyeless Devourer', 'eyeless devourer'],
	['Falcon Knight', 'falcon knight'],
	['Falcon Paladin', 'falcon paladin'],
	['Faun', 'faun'],
	['Feral Sphinx', 'feral sphinx'],
	['Feral Werecrocodile', 'feral werecrocodile'],
	['Feverish Citizen', 'feverish citizen'],
	['Feversleep', 'feversleep'],
	['Filth Toad', 'filth toad'],
	['Fire Devil', 'fire devil'],
	['Fire Elemental', 'fire elemental'],
	['Firestarter', 'firestarter'],
	['Fish', 'fish'],
	['Flamingo', 'flamingo'],
	['Flimsy Lost Soul', 'flimsy lost soul'],
	['Floating Savant', 'floating savant'],
	['Flying Book', 'flying book'],
	['Foam Stalker', 'foam stalker'],
	['Forest Fury', 'forest fury'],
	['Fox', 'fox'],
	['Frazzlemaw', 'frazzlemaw'],
	['Freakish Lost Soul', 'freakish lost soul'],
	['Frost Dragon Hatchling', 'frost dragon hatchling'],
	['Frost Dragon', 'frost dragon'],
	['Frost Flower Asura', 'frost flower asura'],
	['Frost Giant', 'frost giant'],
	['Frost Giantess', 'frost giantess'],
	['Frost Troll', 'frost troll'],
	['Fruit Drop', 'fruit drop'],
	['Furious Fire Elemental', 'furious fire elemental'],
	['Furious Troll', 'furious troll'],
	['Fury', 'fury'],
	['Gang Member', 'gang member'],
	['Gargoyle', 'gargoyle'],
	['Gazer Spectre', 'gazer spectre'],
	['Gazer', 'gazer'],
	['Ghastly Dragon', 'ghastly dragon'],
	['Ghost Wolf', 'ghost wolf'],
	['Ghost', 'ghost'],
	['Ghoul', 'ghoul'],
	['Ghoulish Hyaena', 'ghoulish hyaena'],
	['Giant Spider', 'giant spider'],
	['Gingerbread Man', 'gingerbread man'],
	['Girtablilu Warrior', 'girtablilu warrior'],
	['Gladiator', 'gladiator'],
	['Gloom Maw', 'gloom maw'],
	['Gloom Wolf', 'gloom wolf'],
	['Glooth Anemone', 'glooth anemone'],
	['Glooth Bandit', 'glooth bandit'],
	['Glooth Blob', 'glooth blob'],
	['Glooth Brigand', 'glooth brigand'],
	['Glooth Golem', 'glooth golem'],
	['Gnarlhound', 'gnarlhound'],
	['Goblin Assassin', 'goblin assassin'],
	['Goblin Leader', 'goblin leader'],
	['Goblin Scavenger', 'goblin scavenger'],
	['Goblin', 'goblin'],
	['Goggle Cake', 'goggle cake'],
	['Golden Servant Replica', 'golden servant replica'],
	['Golden Servant', 'golden servant'],
	['Goldhanded Cultist Bride', 'goldhanded cultist bride'],
	['Goldhanded Cultist', 'goldhanded cultist'],
	['Gore Horn', 'gore horn'],
	['Gorerilla', 'gorerilla'],
	['Gorger Inferniarch', 'gorger inferniarch'],
	['Gozzler', 'gozzler'],
	['Grave Guard', 'grave guard'],
	['Grave Robber', 'grave robber'],
	['Gravedigger', 'gravedigger'],
	['Green Djinn', 'green djinn'],
	['Green Frog', 'green frog'],
	['Grim Reaper', 'grim reaper'],
	['Grimeleech', 'grimeleech'],
	['Grynch Clan Goblin', 'grynch clan goblin'],
	['Gryphon', 'gryphon'],
	['Guardian of Tales', 'guardian of tales'],
	['Guzzlemaw', 'guzzlemaw'],
	['Hand of Cursed Fate', 'hand of cursed fate'],
	['Harpy', 'harpy'],
	['Haunted Dragon', 'haunted dragon'],
	['Haunted Hunter', 'haunted hunter'],
	['Haunted Treeling', 'haunted treeling'],
	['Hawk Hopper', 'hawk hopper'],
	['Headpecker', 'headpecker'],
	['Headwalker', 'headwalker'],
	['Hellfire Fighter', 'hellfire fighter'],
	['Hellflayer', 'hellflayer'],
	['Hellhound', 'hellhound'],
	['Hellhunter Inferniarch', 'hellhunter inferniarch'],
	['Hellspawn', 'hellspawn'],
	['Herald of Gloom', 'herald of gloom'],
	['Hero', 'hero'],
	['Hibernal Moth', 'hibernal moth'],
	['Hideous Fungus', 'hideous fungus'],
	['High Voltage Elemental', 'high voltage elemental'],
	['Hive Overseer', 'hive overseer'],
	['Honey Elemental', 'honey elemental'],
	['Honour Guard', 'honour guard'],
	['Horse (Brown)', 'horse (brown)'],
	['Horse (Grey)', 'horse (grey)'],
	['Horse (Taupe)', 'horse (taupe)'],
	['Hot Dog', 'hot dog'],
	['Hulking Carnisylvan', 'hulking carnisylvan'],
	['Hulking Prehemoth', 'hulking prehemoth'],
	['Humongous Fungus', 'humongous fungus'],
	['Hunter', 'hunter'],
	['Husky', 'husky'],
	['Hyaena', 'hyaena'],
	['Hydra', 'hydra'],
	['Ice Dragon', 'ice dragon'],
	['Ice Golem', 'ice golem'],
	['Ice Witch', 'ice witch'],
	['Icecold Book', 'icecold book'],
	['Iceplume Strider', 'iceplume strider'],
	['Iks Ahpututu', 'iks ahpututu'],
	['Iks Aucar', 'iks aucar'],
	['Iks Chuka', 'iks chuka'],
	['Iks Churrascan', 'iks churrascan'],
	['Iks Pututu', 'iks pututu'],
	['Iks Yapunac', 'iks yapunac'],
	['Imperial', 'imperial'],
	['Infected Weeper', 'infected weeper'],
	['Infernal Demon', 'infernal demon'],
	['Infernal Frog', 'infernal frog'],
	['Infernal Phantom', 'infernal phantom'],
	['Infernalist', 'infernalist'],
	['Infernoid Blob', 'infernoid blob'],
	['Infernoid Hound', 'infernoid hound'],
	['Infernoid Soul', 'infernoid soul'],
	['Infernoid Spiritual', 'infernoid spiritual'],
	['Ink Blob', 'ink blob'],
	['Ink Splash', 'ink splash'],
	['Insane Siren', 'insane siren'],
	['Insect Swarm', 'insect swarm'],
	['Insectoid Scout', 'insectoid scout'],
	['Insectoid Worker', 'insectoid worker'],
	['Instable Breach Brood', 'instable breach brood'],
	['Instable Sparkion', 'instable sparkion'],
	['Iron Servant Replica', 'iron servant replica'],
	['Iron Servant', 'iron servant'],
	['Ironblight', 'ironblight'],
	['Island Troll', 'island troll'],
	['Jaracal', 'jaracal'],
	['Jellyfish', 'jellyfish'],
	['Juggernaut', 'juggernaut'],
	['Jungle Moa', 'jungle moa'],
	['Juvenile Bashmu', 'juvenile bashmu'],
	['Killer Caiman', 'killer caiman'],
	['Killer Rabbit', 'killer rabbit'],
	['Knowledge Elemental', 'knowledge elemental'],
	['Kollos', 'kollos'],
	['Kongra', 'kongra'],
	['Lacewing Moth', 'lacewing moth'],
	['Ladybug', 'ladybug'],
	['Lamassu', 'lamassu'],
	['Lancer Beetle', 'lancer beetle'],
	['Larva', 'larva'],
	['Lava Golem', 'lava golem'],
	['Lava Lurker', 'lava lurker'],
	['Lavafungus', 'lavafungus'],
	['Lavaworm', 'lavaworm'],
	['Leaf Golem', 'leaf golem'],
	['Lich', 'lich'],
	['Liodile', 'liodile'],
	['Lion Hydra', 'lion hydra'],
	['Lion', 'lion'],
	['Little Corym Charlatan', 'little corym charlatan'],
	['Lizard Chosen', 'lizard chosen'],
	['Lizard Commander', 'lizard commander'],
	['Lizard Dragon Priest', 'lizard dragon priest'],
	['Lizard Executioner', 'lizard executioner'],
	['Lizard Henchman', 'lizard henchman'],
	['Lizard High Guard', 'lizard high guard'],
	['Lizard Legionnaire', 'lizard legionnaire'],
	['Lizard Magician', 'lizard magician'],
	['Lizard Magistratus', 'lizard magistratus'],
	['Lizard Noble', 'lizard noble'],
	['Lizard Sentinel', 'lizard sentinel'],
	['Lizard Snakecharmer', 'lizard snakecharmer'],
	['Lizard Swordmaster', 'lizard swordmaster'],
	['Lizard Templar', 'lizard templar'],
	['Lizard Zaogun', 'lizard zaogun'],
	['Loricate Orger', 'loricate orger'],
	['Lost Basher', 'lost basher'],
	['Lost Berserker', 'lost berserker'],
	['Lost Exile', 'lost exile'],
	['Lost Husher', 'lost husher'],
	['Lost Soul', 'lost soul'],
	['Lost Thrower', 'lost thrower'],
	['Lumbering Carnivor', 'lumbering carnivor'],
	['Mad Scientist', 'mad scientist'],
	['Magma Crawler', 'magma crawler'],
	['Makara', 'makara'],
	['Mammoth', 'mammoth'],
	['Manta Ray', 'manta ray'],
	['Manticore', 'manticore'],
	['Mantosaurus', 'mantosaurus'],
	['Many Faces', 'many faces'],
	['Marid', 'marid'],
	['Marsh Stalker', 'marsh stalker'],
	['Massive Earth Elemental', 'massive earth elemental'],
	['Massive Energy Elemental', 'massive energy elemental'],
	['Massive Fire Elemental', 'massive fire elemental'],
	['Massive Water Elemental', 'massive water elemental'],
	['Mean Lost Soul', 'mean lost soul'],
	['Meandering Mushroom', 'meandering mushroom'],
	['Medusa', 'medusa'],
	['Mega Dragon', 'mega dragon'],
	['Menacing Carnivor', 'menacing carnivor'],
	['Mercurial Menace', 'mercurial menace'],
	['Mercury Blob', 'mercury blob'],
	['Merlkin', 'merlkin'],
	['Metal Gargoyle', 'metal gargoyle'],
	['Midnight Asura', 'midnight asura'],
	['Midnight Panther', 'midnight panther'],
	['Midnight Spawn', 'midnight spawn'],
	['Midnight Warrior', 'midnight warrior'],
	['Minotaur Amazon', 'minotaur amazon'],
	['Minotaur Archer', 'minotaur archer'],
	['Minotaur Cult Follower', 'minotaur cult follower'],
	['Minotaur Cult Prophet', 'minotaur cult prophet'],
	['Minotaur Cult Zealot', 'minotaur cult zealot'],
	['Minotaur Guard', 'minotaur guard'],
	['Minotaur Hunter', 'minotaur hunter'],
	['Minotaur Invader', 'minotaur invader'],
	['Minotaur Mage', 'minotaur mage'],
	['Minotaur', 'minotaur'],
	['Misguided Bully', 'misguided bully'],
	['Misguided Thief', 'misguided thief'],
	['Mitmah Scout', 'mitmah scout'],
	['Mitmah Seer', 'mitmah seer'],
	['Modified Gnarlhound', 'modified gnarlhound'],
	['Mole', 'mole'],
	['Monk', 'monk'],
	['Moohtant', 'moohtant'],
	['Moonspawn Blightspitter', 'moonspawn blightspitter'],
	['Moonspawn Oozecrown', 'moonspawn oozecrown'],
	['Moonstone Excavator', 'moonstone excavator'],
	['Moonstone Overseer', 'moonstone overseer'],
	['Mould Phantom', 'mould phantom'],
	['Muglex Clan Assassin', 'muglex clan assassin'],
	['Muglex Clan Footman', 'muglex clan footman'],
	['Mummy', 'mummy'],
	['Mushroom Sniffer', 'mushroom sniffer'],
	['Mutated Bat', 'mutated bat'],
	['Mutated Human', 'mutated human'],
	['Mutated Rat', 'mutated rat'],
	['Mutated Tiger', 'mutated tiger'],
	['Mycobiontic Beetle', 'mycobiontic beetle'],
	['Naga Archer', 'naga archer'],
	['Naga Warrior', 'naga warrior'],
	['Necromancer', 'necromancer'],
	['Nibblemaw', 'nibblemaw'],
	['Night Harpy', 'night harpy'],
	['Nightfiend', 'nightfiend'],
	['Nighthunter', 'nighthunter'],
	['Nightmare Scion', 'nightmare scion'],
	['Nightmare', 'nightmare'],
	['Nightslayer', 'nightslayer'],
	['Nightstalker', 'nightstalker'],
	['Noble Lion', 'noble lion'],
	['Nomad (Basic)', 'nomad (basic)'],
	['Nomad (Blue)', 'nomad (blue)'],
	['Nomad (Female)', 'nomad (female)'],
	['Norcferatu Heartless', 'norcferatu heartless'],
	['Norcferatu Nightweaver', 'norcferatu nightweaver'],
	['Northern Pike', 'northern pike'],
	['Novice of the Cult', 'novice of the cult'],
	['Noxious Ripptor', 'noxious ripptor'],
	['Nymph', 'nymph'],
	['Ogre Brute', 'ogre brute'],
	['Ogre Rowdy', 'ogre rowdy'],
	['Ogre Ruffian', 'ogre ruffian'],
	['Ogre Sage', 'ogre sage'],
	['Ogre Savage', 'ogre savage'],
	['Ogre Shaman', 'ogre shaman'],
	['Omnivora', 'omnivora'],
	['Oozing Carcass', 'oozing carcass'],
	['Oozing Corpus', 'oozing corpus'],
	['Orc Berserker', 'orc berserker'],
	['Orc Cult Fanatic', 'orc cult fanatic'],
	['Orc Cult Inquisitor', 'orc cult inquisitor'],
	['Orc Cult Minion', 'orc cult minion'],
	['Orc Cult Priest', 'orc cult priest'],
	['Orc Cultist', 'orc cultist'],
	['Orc Leader', 'orc leader'],
	['Orc Marauder', 'orc marauder'],
	['Orc Rider', 'orc rider'],
	['Orc Shaman', 'orc shaman'],
	['Orc Spearman', 'orc spearman'],
	['Orc Warlord', 'orc warlord'],
	['Orc Warrior', 'orc warrior'],
	['Orc', 'orc'],
	['Orchid Frog', 'orchid frog'],
	['Orclops Bloodbreaker', 'orclops bloodbreaker'],
	['Orclops Doomhauler', 'orclops doomhauler'],
	['Orclops Ravager', 'orclops ravager'],
	['Orewalker', 'orewalker'],
	['Orger', 'orger'],
	['Panda', 'panda'],
	['Parder', 'parder'],
	['Parrot', 'parrot'],
	['Penguin', 'penguin'],
	['Percht', 'percht'],
	['Phantasm', 'phantasm'],
	['Pig', 'pig'],
	['Pigeon', 'pigeon'],
	['Pirat Bombardier', 'pirat bombardier'],
	['Pirat Cutthroat', 'pirat cutthroat'],
	['Pirat Mate', 'pirat mate'],
	['Pirat Scoundrel', 'pirat scoundrel'],
	['Pirate Buccaneer', 'pirate buccaneer'],
	['Pirate Cook', 'pirate cook'],
	['Pirate Corsair', 'pirate corsair'],
	['Pirate Cutthroat', 'pirate cutthroat'],
	['Pirate Ghost', 'pirate ghost'],
	['Pirate Gunner', 'pirate gunner'],
	['Pirate Marauder', 'pirate marauder'],
	['Pirate Navigator', 'pirate navigator'],
	['Pirate Quartermaster', 'pirate quartermaster'],
	['Pirate Skeleton', 'pirate skeleton'],
	['Pixie', 'pixie'],
	['Plaguesmith', 'plaguesmith'],
	['Poacher', 'poacher'],
	['Poison Spider', 'poison spider'],
	['Poisonous Carnisylvan', 'poisonous carnisylvan'],
	['Polar Bear', 'polar bear'],
	['Pooka', 'pooka'],
	['Priestess of the Wild Sun', 'priestess of the wild sun'],
	['Priestess', 'priestess'],
	['Putrid Mummy', 'putrid mummy'],
	['Quara Constrictor Scout', 'quara constrictor scout'],
	['Quara Constrictor', 'quara constrictor'],
	['Quara Hydromancer Scout', 'quara hydromancer scout'],
	['Quara Hydromancer', 'quara hydromancer'],
	['Quara Looter', 'quara looter'],
	['Quara Mantassin Scout', 'quara mantassin scout'],
	['Quara Mantassin', 'quara mantassin'],
	['Quara Pincher Scout', 'quara pincher scout'],
	['Quara Pincher', 'quara pincher'],
	['Quara Plunderer', 'quara plunderer'],
	['Quara Predator Scout', 'quara predator scout'],
	['Quara Predator', 'quara predator'],
	['Quara Raider', 'quara raider'],
	['Rabbit', 'rabbit'],
	['Rabid Wolf', 'rabid wolf'],
	['Radiant Acolyte', 'radiant acolyte'],
	['Radiant Inquisitor', 'radiant inquisitor'],
	['Radiant Paragon', 'radiant paragon'],
	['Radiant Templar', 'radiant templar'],
	['Radiant Warden', 'radiant warden'],
	['Radiant Zealot', 'radiant zealot'],
	['Rage Squid', 'rage squid'],
	['Ragged Rabid Wolf', 'ragged rabid wolf'],
	['Raging Fire', 'raging fire'],
	['Rat', 'rat'],
	['Raubritter Chastener', 'raubritter chastener'],
	['Raubritter Marksman', 'raubritter marksman'],
	['Raubritter Skirmisher', 'raubritter skirmisher'],
	['Ravenous Lava Lurker', 'ravenous lava lurker'],
	['Reality Reaver', 'reality reaver'],
	['Redeemed Soul', 'redeemed soul'],
	['Renegade Knight', 'renegade knight'],
	['Renegade Quara Constrictor', 'renegade quara constrictor'],
	['Renegade Quara Hydromancer', 'renegade quara hydromancer'],
	['Renegade Quara Mantassin', 'renegade quara mantassin'],
	['Renegade Quara Pincher', 'renegade quara pincher'],
	['Renegade Quara Predator', 'renegade quara predator'],
	['Retching Horror', 'retching horror'],
	['Rhindeer', 'rhindeer'],
	['Ripper Spectre', 'ripper spectre'],
	['Roaming Dread', 'roaming dread'],
	['Roaring Lion', 'roaring lion'],
	['Roast Pork', 'roast pork'],
	['Rootthing Amber Shaper', 'rootthing amber shaper'],
	['Rootthing Bug Tracker', 'rootthing bug tracker'],
	['Rootthing Nutshell', 'rootthing nutshell'],
	['Rorc', 'rorc'],
	['Rot Elemental', 'rot elemental'],
	['Rotten Golem', 'rotten golem'],
	['Rotten Man-Maggot', 'rotten man-maggot'],
	['Rotworm', 'rotworm'],
	['Rustheap Golem', 'rustheap golem'],
	['Sabretooth', 'sabretooth'],
	['Sacred Spider', 'sacred spider'],
	['Salamander', 'salamander'],
	['Sandcrawler', 'sandcrawler'],
	['Sandstone Scorpion', 'sandstone scorpion'],
	['Scarab', 'scarab'],
	['Schiach', 'schiach'],
	['Scorpion', 'scorpion'],
	['Sea Captain', 'sea captain'],
	['Sea Serpent', 'sea serpent'],
	['Seacrest Serpent', 'seacrest serpent'],
	['Seagull', 'seagull'],
	['Serpent Spawn', 'serpent spawn'],
	['Shaburak Demon', 'shaburak demon'],
	['Shaburak Lord', 'shaburak lord'],
	['Shaburak Prince', 'shaburak prince'],
	['Shadow Hound', 'shadow hound'],
	['Shadow Pupil', 'shadow pupil'],
	['Shaper Matriarch', 'shaper matriarch'],
	['Shark', 'shark'],
	['Sheep', 'sheep'],
	['Shell Drake', 'shell drake'],
	['Shock Head', 'shock head'],
	['Shrieking Cry-Stal', 'shrieking cry-stal'],
	['Sibang', 'sibang'],
	['Sight of Surrender', 'sight of surrender'],
	['Silencer', 'silencer'],
	['Silver Rabbit', 'silver rabbit'],
	['Silverfrost Sentinel', 'silverfrost sentinel'],
	['Sineater Inferniarch', 'sineater inferniarch'],
	['Skeleton Elite Warrior', 'skeleton elite warrior'],
	['Skeleton Warrior', 'skeleton warrior'],
	['Skeleton', 'skeleton'],
	['Skunk', 'skunk'],
	['Slime', 'slime'],
	['Slug', 'slug'],
	['Smuggler', 'smuggler'],
	['Snake', 'snake'],
	['Son of Verminor', 'son of verminor'],
	['Sopping Carcass', 'sopping carcass'],
	['Sopping Corpus', 'sopping corpus'],
	['Soul-Broken Harbinger', 'soul-broken harbinger'],
	['Souleater', 'souleater'],
	['Sparkion', 'sparkion'],
	['Spectre', 'spectre'],
	['Spellreaper Inferniarch', 'spellreaper inferniarch'],
	['Sphinx', 'sphinx'],
	['Spider', 'spider'],
	['Spidris Elite', 'spidris elite'],
	['Spidris', 'spidris'],
	['Spiky Carnivor', 'spiky carnivor'],
	['Spit Nettle', 'spit nettle'],
	['Spitter', 'spitter'],
	['Squid Warden', 'squid warden'],
	['Squidgy Slime', 'squidgy slime'],
	['Squirrel', 'squirrel'],
	['Stabilizing Dread Intruder', 'stabilizing dread intruder'],
	['Stabilizing Reality Reaver', 'stabilizing reality reaver'],
	['Stag', 'stag'],
	['Stalker', 'stalker'],
	['Stalking Stalk', 'stalking stalk'],
	['Stampor', 'stampor'],
	['Starving Wolf', 'starving wolf'],
	['Stone Devourer', 'stone devourer'],
	['Stone Golem', 'stone golem'],
	['Stone Rhino', 'stone rhino'],
	['Stonerefiner', 'stonerefiner'],
	['Streaked Devourer', 'streaked devourer'],
	['Sugar Cube Worker', 'sugar cube worker'],
	['Sugar Cube', 'sugar cube'],
	['Sulphider', 'sulphider'],
	['Sulphur Spouter', 'sulphur spouter'],
	['Swamp Troll', 'swamp troll'],
	['Swampling', 'swampling'],
	['Swan Maiden', 'swan maiden'],
	['Swarmer', 'swarmer'],
	['Tainted Soul', 'tainted soul'],
	['Tarantula', 'tarantula'],
	['Tarnished Spirit', 'tarnished spirit'],
	['Terramite', 'terramite'],
	['Terrified Elephant', 'terrified elephant'],
	['Terror Bird', 'terror bird'],
	['Terrorsleep', 'terrorsleep'],
	['Thanatursus', 'thanatursus'],
	['Thornback Tortoise', 'thornback tortoise'],
	['Thornfire Wolf', 'thornfire wolf'],
	['Tiger', 'tiger'],
	['Toad', 'toad'],
	['Tomb Servant', 'tomb servant'],
	['Tortoise', 'tortoise'],
	['Tremendous Tyrant', 'tremendous tyrant'],
	['Troll Champion', 'troll champion'],
	['Troll Guard', 'troll guard'],
	['Troll Legionnaire', 'troll legionnaire'],
	['Troll', 'troll'],
	['True Dawnfire Asura', 'true dawnfire asura'],
	['True Feverbloom Asura', 'true feverbloom asura'],
	['True Frost Flower Asura', 'true frost flower asura'],
	['True Midnight Asura', 'true midnight asura'],
	['Truffle Cook', 'truffle cook'],
	['Truffle', 'truffle'],
	['Tunnel Tyrant', 'tunnel tyrant'],
	['Turbulent Elemental', 'turbulent elemental'],
	['Twisted Pooka', 'twisted pooka'],
	['Twisted Shaper', 'twisted shaper'],
	['Two-Headed Turtle', 'two-headed turtle'],
	['Undead Cavebear', 'undead cavebear'],
	['Undead Dragon', 'undead dragon'],
	['Undead Elite Gladiator', 'undead elite gladiator'],
	['Undead Gladiator', 'undead gladiator'],
	['Undead Jester', 'undead jester'],
	['Undead Mine Worker', 'undead mine worker'],
	['Undead Prospector', 'undead prospector'],
	['Undertaker', 'undertaker'],
	['Usurper Archer', 'usurper archer'],
	['Usurper Knight', 'usurper knight'],
	['Usurper Warlock', 'usurper warlock'],
	['Valkyrie', 'valkyrie'],
	['Vampire Bride', 'vampire bride'],
	['Vampire Pig', 'vampire pig'],
	['Vampire Viscount', 'vampire viscount'],
	['Vampire', 'vampire'],
	['Varg', 'varg'],
	['Varnished Diremaw', 'varnished diremaw'],
	['Venerable Girtablilu', 'venerable girtablilu'],
	['Vexclaw', 'vexclaw'],
	['Vibrant Phantom', 'vibrant phantom'],
	['Vicious Manbat', 'vicious manbat'],
	['Vicious Squire', 'vicious squire'],
	['Vile Grandmaster', 'vile grandmaster'],
	['Vulcongra', 'vulcongra'],
	['Wafer Paper Butterfly', 'wafer paper butterfly'],
	['Wailing Widow', 'wailing widow'],
	['Walker', 'walker'],
	['Walking Dread', 'walking dread'],
	['Walking Pillar', 'walking pillar'],
	['Wandering Pillar', 'wandering pillar'],
	['War Golem', 'war golem'],
	['War Wolf', 'war wolf'],
	['Wardragon', 'wardragon'],
	['Warlock', 'warlock'],
	['Wasp', 'wasp'],
	['Waspoid', 'waspoid'],
	['Water Buffalo', 'water buffalo'],
	['Water Elemental', 'water elemental'],
	['Weakened Frazzlemaw', 'weakened frazzlemaw'],
	['Weeper', 'weeper'],
	['Werebadger', 'werebadger'],
	['Werebear', 'werebear'],
	['Wereboar', 'wereboar'],
	['Werecrocodile', 'werecrocodile'],
	['Werefox', 'werefox'],
	['Werehyaena Shaman', 'werehyaena shaman'],
	['Werehyaena', 'werehyaena'],
	['Werelion', 'werelion'],
	['Werelioness', 'werelioness'],
	['Werepanther', 'werepanther'],
	['Weretiger', 'weretiger'],
	['Werewolf', 'werewolf'],
	['White Deer', 'white deer'],
	['White Lion', 'white lion'],
	['White Shade', 'white shade'],
	['White Tiger', 'white tiger'],
	['White Weretiger', 'white weretiger'],
	['Wiggler', 'wiggler'],
	['Wild Horse', 'wild horse'],
	['Wild Warrior', 'wild warrior'],
	['Wilting Leaf Golem', 'wilting leaf golem'],
	['Winged Jaracal', 'winged jaracal'],
	['Winter Wolf', 'winter wolf'],
	['Wisp', 'wisp'],
	['Witch', 'witch'],
	['Wolf', 'wolf'],
	['Worker Golem', 'worker golem'],
	['Worm Priestess', 'worm priestess'],
	['Wyrm', 'wyrm'],
	['Wyvern', 'wyvern'],
	['Yeti', 'yeti'],
	['Yielothax', 'yielothax'],
	['Young Goanna', 'young goanna'],
	['Young Sea Serpent', 'young sea serpent'],
	['Zombie', 'zombie'],
	["Druid's Apparition", "druid's apparition"],
	["Knight's Apparition", "knight's apparition"],
	["Monk's Apparition", "monk's apparition"],
	["Mooh'tah Warrior", "mooh'tah warrior"],
	["Mooh'Tah Warrior", "mooh'tah warrior"],
	["Paladin's Apparition", "paladin's apparition"],
	["Sorcerer's Apparition", "sorcerer's apparition"],
]);

export const toPrettyName = (uglyName) => {
	const prettyName = uglyToPrettyNames.get(uglyName);
	if (!prettyName) {
		console.log(`Unknown pretty name for uglyName=${JSON.stringify(uglyName)}`);
		return uglyName;
	}
	return prettyName;
};

export const uglyCreatureNames = [...uglyToPrettyNames.keys()];
export const prettyCreatureNames = [...uglyToPrettyNames.values()];
