import * as fs from 'node:fs/promises';

const CREATURES = [
	'Abyssal Calamary',
	'Acid Blob',
	'Acolyte of the Cult',
	'Adept of the Cult',
	'Adult Goanna',
	'Adventurer',
	'Afflicted Strider',
	'Agrestic Chicken',
	'Amazon',
	'Ancient Scarab',
	'Animated Feather',
	'Animated Snowman',
	'Arachnophobica',
	'Arctic Faun',
	'Armadile',
	'Askarak Demon',
	'Askarak Lord',
	'Askarak Prince',
	'Assassin',
	'Azure Frog',
	'Badger',
	'Baleful Bunny',
	'Bandit',
	'Banshee',
	'Barbarian Bloodwalker',
	'Barbarian Brutetamer',
	'Barbarian Headsplitter',
	'Barbarian Skullhunter',
	'Barkless Devotee',
	'Barkless Fanatic',
	'Bashmu',
	'Bat',
	'Bear',
	'Behemoth',
	'Bellicose Orger',
	'Berserker Chicken',
	'Betrayed Wraith',
	'Biting Book',
	'Black Sheep',
	'Black Sphinx Acolyte',
	'Blemished Spawn',
	'Blightwalker',
	'Blood Beast',
	'Blood Crab',
	'Blood Hand',
	'Blood Priest',
	'Blue Djinn',
	'Boar Man',
	'Boar',
	'Bog Frog',
	'Bog Raider',
	'Bonebeast',
	'Bonelord',
	'Bony Sea Devil',
	'Boogy',
	'Brachiodemon',
	'Brain Squid',
	'Braindeath',
	'Branchy Crawler',
	'Breach Brood',
	'Brimstone Bug',
	'Broken Shaper',
	'Bug',
	'Burning Book',
	'Burning Gladiator',
	'Burster Spectre',
	'Calamary',
	'Capricious Phantom',
	'Carniphila',
	'Carnivostrich',
	'Carrion Worm',
	'Cat',
	'Cave Chimera',
	'Cave Devourer',
	'Cave Parrot',
	'Cave Rat',
	'Centipede',
	'Chakoya Toolshaper',
	'Chakoya Tribewarden',
	'Chakoya Windcaller',
	'Chasm Spawn',
	'Chicken',
	'Choking Fear',
	'Clay Guardian',
	'Cliff Strider',
	'Cloak of Terror',
	'Clomp',
	'Cobra Assassin',
	'Cobra Scout',
	'Cobra Vizier',
	'Cobra',
	'Coral Frog',
	'Corym Charlatan',
	'Corym Skirmisher',
	'Corym Vanguard',
	'Courage Leech',
	'Cow',
	'Crab',
	'Crape Man',
	'Crawler',
	'Crazed Beggar',
	'Crazed Summer Rearguard',
	'Crazed Summer Vanguard',
	'Crazed Winter Rearguard',
	'Crazed Winter Vanguard',
	'Crimson Frog',
	'Crocodile',
	'Crypt Defiler',
	'Crypt Shambler',
	'Crypt Warden',
	'Crypt Warrior',
	'Crystal Spider',
	'Crystalcrusher',
	'Cult Believer',
	'Cult Enforcer',
	'Cult Scholar',
	'Cursed Ape',
	'Cursed Book',
	'Cursed Prospector',
	'Cyclops Drone',
	'Cyclops Smith',
	'Cyclops',
	'Damaged Crystal Golem',
	'Damaged Worker Golem',
	'Dark Apprentice',
	'Dark Carnisylvan',
	'Dark Faun',
	'Dark Magician',
	'Dark Monk',
	'Dark Torturer',
	'Dawnfire Asura',
	'Death Blob',
	'Death Priest',
	'Deathling Scout',
	'Deathling Spellsinger',
	'Deepling Brawler',
	'Deepling Elite',
	'Deepling Guard',
	'Deepling Master Librarian',
	'Deepling Scout',
	'Deepling Spellsinger',
	'Deepling Tyrant',
	'Deepling Warrior',
	'Deepling Worker',
	'Deepsea Blood Crab',
	'Deepworm',
	'Deer',
	'Defiler',
	'Demon Outcast',
	'Demon Parrot',
	'Demon Skeleton',
	'Demon',
	'Destroyer',
	'Devourer',
	'Diabolic Imp',
	'Diamond Servant Replica',
	'Diremaw',
	'Distorted Phantom',
	'Dog',
	'Doom Deer',
	'Dragon Hatchling',
	'Dragon Lord Hatchling',
	'Dragon Lord',
	'Dragon',
	'Dragonling',
	'Draken Abomination',
	'Draken Elite',
	'Draken Spellweaver',
	'Draken Warmaster',
	'Dread Intruder',
	'Drillworm',
	'Dromedary',
	"Druid's Apparition",
	'Dwarf Geomancer',
	'Dwarf Guard',
	'Dwarf Henchman',
	'Dwarf Soldier',
	'Dwarf',
	'Dworc Fleshhunter',
	'Dworc Venomsniper',
	'Dworc Voodoomaster',
	'Earth Elemental',
	'Efreet',
	'Elder Bonelord',
	'Elder Forest Fury',
	'Elder Mummy',
	'Elder Wyrm',
	'Elephant',
	'Elf Arcanist',
	'Elf Scout',
	'Elf',
	'Emerald Damselfly',
	'Emerald Tortoise',
	'Energetic Book',
	'Energuardian of Tales',
	'Energy Elemental',
	'Enfeebled Silencer',
	'Enlightened of the Cult',
	'Enraged Crystal Golem',
	'Enslaved Dwarf',
	'Eternal Guardian',
	'Evil Prospector',
	'Evil Sheep Lord',
	'Evil Sheep',
	'Execowtioner',
	'Exotic Bat',
	'Exotic Cave Spider',
	'Eyeless Devourer',
	'Falcon Knight',
	'Falcon Paladin',
	'Faun',
	'Feral Sphinx',
	'Feverish Citizen',
	'Feversleep',
	'Filth Toad',
	'Fire Devil',
	'Fire Elemental',
	'Firestarter',
	'Flamingo',
	'Flimsy Lost Soul',
	'Floating Savant',
	'Flying Book',
	'Foam Stalker',
	'Forest Fury',
	'Fox',
	'Frazzlemaw',
	'Freakish Lost Soul',
	'Frost Dragon Hatchling',
	'Frost Dragon',
	'Frost Flower Asura',
	'Frost Giant',
	'Frost Giantess',
	'Frost Troll',
	'Furious Fire Elemental',
	'Furious Troll',
	'Fury',
	'Gang Member',
	'Gargoyle',
	'Gazer Spectre',
	'Gazer',
	'Ghastly Dragon',
	'Ghost Wolf',
	'Ghost',
	'Ghoul',
	'Ghoulish Hyaena',
	'Giant Spider',
	'Girtablilu Warrior',
	'Gladiator',
	'Gloom Wolf',
	'Glooth Anemone',
	'Glooth Bandit',
	'Glooth Blob',
	'Glooth Brigand',
	'Glooth Golem',
	'Gnarlhound',
	'Goblin Assassin',
	'Goblin Scavenger',
	'Goblin',
	'Golden Servant Replica',
	'Goldhanded Cultist Bride',
	'Goldhanded Cultist',
	'Gore Horn',
	'Gorerilla',
	'Gozzler',
	'Grave Guard',
	'Grave Robber',
	'Gravedigger',
	'Green Djinn',
	'Green Frog',
	'Grim Reaper',
	'Grimeleech',
	'Gryphon',
	'Guardian of Tales',
	'Guzzlemaw',
	'Hand of Cursed Fate',
	'Harpy',
	'Haunted Dragon',
	'Haunted Treeling',
	'Headpecker',
	'Hellfire Fighter',
	'Hellflayer',
	'Hellhound',
	'Hellspawn',
	'Hero',
	'Hibernal Moth',
	'Hideous Fungus',
	'High Voltage Elemental',
	'Hive Overseer',
	'Honour Guard',
	'Hot Dog',
	'Hulking Carnisylvan',
	'Hulking Prehemoth',
	'Humongous Fungus',
	'Hunter',
	'Husky',
	'Hyaena',
	'Hydra',
	'Ice Dragon',
	'Ice Golem',
	'Ice Witch',
	'Icecold Book',
	'Iks Aucar',
	'Iks Chuka',
	'Iks Churrascan',
	'Iks Pututu',
	'Infected Weeper',
	'Infernal Demon',
	'Infernal Frog',
	'Infernal Phantom',
	'Infernalist',
	'Ink Blob',
	'Insane Siren',
	'Insectoid Scout',
	'Insectoid Worker',
	'Instable Breach Brood',
	'Instable Sparkion',
	'Iron Servant Replica',
	'Ironblight',
	'Island Troll',
	'Jellyfish',
	'Juggernaut',
	'Jungle Moa',
	'Juvenile Bashmu',
	'Killer Caiman',
	'Killer Rabbit',
	"Knight's Apparition",
	'Knowledge Elemental',
	'Kollos',
	'Kongra',
	'Lacewing Moth',
	'Ladybug',
	'Lamassu',
	'Lancer Beetle',
	'Larva',
	'Lava Golem',
	'Lava Lurker',
	'Lavafungus',
	'Lavaworm',
	'Leaf Golem',
	'Lich',
	'Liodile',
	'Lion',
	'Little Corym Charlatan',
	'Lizard Chosen',
	'Lizard Dragon Priest',
	'Lizard High Guard',
	'Lizard Legionnaire',
	'Lizard Magistratus',
	'Lizard Noble',
	'Lizard Sentinel',
	'Lizard Snakecharmer',
	'Lizard Templar',
	'Lizard Zaogun',
	'Loricate Orger',
	'Lost Basher',
	'Lost Berserker',
	'Lost Exile',
	'Lost Husher',
	'Lost Soul',
	'Lost Thrower',
	'Lumbering Carnivor',
	'Mad Scientist',
	'Magma Crawler',
	'Makara',
	'Mammoth',
	'Manta Ray',
	'Manticore',
	'Mantosaurus',
	'Many Faces',
	'Marid',
	'Marsh Stalker',
	'Massive Earth Elemental',
	'Massive Energy Elemental',
	'Massive Fire Elemental',
	'Massive Water Elemental',
	'Mean Lost Soul',
	'Medusa',
	'Menacing Carnivor',
	'Mercurial Menace',
	'Mercury Blob',
	'Merlkin',
	'Metal Gargoyle',
	'Midnight Asura',
	'Minotaur Amazon',
	'Minotaur Archer',
	'Minotaur Cult Follower',
	'Minotaur Cult Prophet',
	'Minotaur Cult Zealot',
	'Minotaur Guard',
	'Minotaur Hunter',
	'Minotaur Invader',
	'Minotaur Mage',
	'Minotaur',
	'Misguided Bully',
	'Misguided Thief',
	'Modified Gnarlhound',
	'Mole',
	'Monk',
	"Mooh'tah Warrior",
	'Moohtant',
	'Mould Phantom',
	'Mummy',
	'Mushroom Sniffer',
	'Mutated Bat',
	'Mutated Human',
	'Mutated Rat',
	'Mutated Tiger',
	'Naga Archer',
	'Naga Warrior',
	'Necromancer',
	'Nighthunter',
	'Nightmare Scion',
	'Nightmare',
	'Nightstalker',
	'Noble Lion',
	'Nomad (Basic)',
	'Novice of the Cult',
	'Noxious Ripptor',
	'Nymph',
	'Ogre Brute',
	'Ogre Rowdy',
	'Ogre Ruffian',
	'Ogre Sage',
	'Ogre Savage',
	'Ogre Shaman',
	'Omnivora',
	'Orc Berserker',
	'Orc Cult Fanatic',
	'Orc Cult Inquisitor',
	'Orc Cult Minion',
	'Orc Cult Priest',
	'Orc Cultist',
	'Orc Leader',
	'Orc Marauder',
	'Orc Rider',
	'Orc Shaman',
	'Orc Spearman',
	'Orc Warlord',
	'Orc Warrior',
	'Orc',
	'Orchid Frog',
	'Orclops Doomhauler',
	'Orclops Ravager',
	'Orewalker',
	'Orger',
	"Paladin's Apparition",
	'Panda',
	'Parder',
	'Parrot',
	'Penguin',
	'Percht',
	'Phantasm',
	'Pig',
	'Pigeon',
	'Pirat Bombardier',
	'Pirat Cutthroat',
	'Pirat Mate',
	'Pirat Scoundrel',
	'Pirate Buccaneer',
	'Pirate Corsair',
	'Pirate Cutthroat',
	'Pirate Ghost',
	'Pirate Marauder',
	'Pirate Skeleton',
	'Pixie',
	'Plaguesmith',
	'Poacher',
	'Poison Spider',
	'Poisonous Carnisylvan',
	'Polar Bear',
	'Pooka',
	'Priestess of the Wild Sun',
	'Priestess',
	'Putrid Mummy',
	'Quara Constrictor Scout',
	'Quara Constrictor',
	'Quara Hydromancer Scout',
	'Quara Hydromancer',
	'Quara Mantassin Scout',
	'Quara Mantassin',
	'Quara Pincher Scout',
	'Quara Pincher',
	'Quara Predator Scout',
	'Quara Predator',
	'Rabbit',
	'Rage Squid',
	'Rat',
	'Ravenous Lava Lurker',
	'Reality Reaver',
	'Redeemed Soul',
	'Renegade Knight',
	'Renegade Quara Constrictor',
	'Renegade Quara Hydromancer',
	'Renegade Quara Mantassin',
	'Renegade Quara Pincher',
	'Renegade Quara Predator',
	'Retching Horror',
	'Rhindeer',
	'Ripper Spectre',
	'Roaring Lion',
	'Roast Pork',
	'Rorc',
	'Rot Elemental',
	'Rotten Golem',
	'Rotworm',
	'Rustheap Golem',
	'Sabretooth',
	'Sacred Spider',
	'Salamander',
	'Sandcrawler',
	'Sandstone Scorpion',
	'Scarab',
	'Schiach',
	'Scorpion',
	'Sea Serpent',
	'Seacrest Serpent',
	'Seagull',
	'Serpent Spawn',
	'Shaburak Demon',
	'Shaburak Lord',
	'Shaburak Prince',
	'Shadow Pupil',
	'Shaper Matriarch',
	'Shark',
	'Sheep',
	'Shock Head',
	'Shrieking Cry-Stal',
	'Sibang',
	'Sight of Surrender',
	'Silencer',
	'Silver Rabbit',
	'Skeleton Elite Warrior',
	'Skeleton Warrior',
	'Skeleton',
	'Skunk',
	'Slug',
	'Smuggler',
	'Snake',
	"Sorcerer's Apparition",
	'Soul-Broken Harbinger',
	'Souleater',
	'Sparkion',
	'Spectre',
	'Sphinx',
	'Spider',
	'Spidris Elite',
	'Spidris',
	'Spiky Carnivor',
	'Spit Nettle',
	'Spitter',
	'Squid Warden',
	'Squirrel',
	'Stabilizing Dread Intruder',
	'Stabilizing Reality Reaver',
	'Stalker',
	'Stalking Stalk',
	'Stampor',
	'Starving Wolf',
	'Stone Devourer',
	'Stone Golem',
	'Stone Rhino',
	'Stonerefiner',
	'Streaked Devourer',
	'Sulphider',
	'Sulphur Spouter',
	'Swamp Troll',
	'Swampling',
	'Swan Maiden',
	'Swarmer',
	'Tainted Soul',
	'Tarantula',
	'Tarnished Spirit',
	'Terramite',
	'Terrified Elephant',
	'Terror Bird',
	'Terrorsleep',
	'Thanatursus',
	'Thornback Tortoise',
	'Tiger',
	'Toad',
	'Tomb Servant',
	'Tortoise',
	'Tremendous Tyrant',
	'Troll Champion',
	'Troll Legionnaire',
	'Troll',
	'True Dawnfire Asura',
	'True Frost Flower Asura',
	'True Midnight Asura',
	'Tunnel Tyrant',
	'Turbulent Elemental',
	'Twisted Pooka',
	'Twisted Shaper',
	'Two-Headed Turtle',
	'Undead Dragon',
	'Undead Elite Gladiator',
	'Undead Gladiator',
	'Undead Mine Worker',
	'Undead Prospector',
	'Undertaker',
	'Usurper Archer',
	'Usurper Knight',
	'Usurper Warlock',
	'Valkyrie',
	'Vampire Bride',
	'Vampire Pig',
	'Vampire Viscount',
	'Vampire',
	'Varnished Diremaw',
	'Venerable Girtablilu',
	'Vexclaw',
	'Vibrant Phantom',
	'Vicious Squire',
	'Vile Grandmaster',
	'Vulcongra',
	'Wailing Widow',
	'Walker',
	'War Golem',
	'War Wolf',
	'Warlock',
	'Wasp',
	'Waspoid',
	'Water Elemental',
	'Weakened Frazzlemaw',
	'Weeper',
	'Werebadger',
	'Werebear',
	'Wereboar',
	'Werefox',
	'Werehyaena Shaman',
	'Werehyaena',
	'Werelion',
	'Werelioness',
	'Werewolf',
	'White Lion',
	'White Shade',
	'Wiggler',
	'Wild Warrior',
	'Wilting Leaf Golem',
	'Winter Wolf',
	'Wisp',
	'Witch',
	'Wolf',
	'Worker Golem',
	'Worm Priestess',
	'Wyrm',
	'Wyvern',
	'Yielothax',
	'Young Goanna',
	'Young Sea Serpent',
	'Zombie',
];

const handleCreature = async (slug) => {
	const url = `https://tibia.fandom.com/api.php?action=query&gaplimit=5&prop=revisions&rvprop=content&format=json&titles=Loot_Statistics:${slug}`;
	const response = await fetch(url);
	const data = await response.json();
	const pages = data.query.pages;
	const firstKey = Object.keys(pages)[0];
	const firstPage = pages[firstKey];
	if (!Object.hasOwn(firstPage, 'revisions')) {
		console.log('Missing `revisions` for', url);
		return {};
	}
	const revision = firstPage.revisions[0];
	const content = revision['*'];
	const lines = content.split('\n');
	const result = {
		monsterName: '',
		timesKilled: 0,
		items: [], // { itemName: '', timesDropped: 0 }
	};
	for (const line of lines) {
		if (line.startsWith('}}')) break; // End of Loot2 block.
		if (!line.startsWith('|')) continue;
		if (line.startsWith('|version=')) continue;
		if (line.startsWith('|Light=')) continue;
		if (line.startsWith('|Empty,')) continue;
		if (line.startsWith('|kills=')) {
			result.timesKilled = Number(line.replace('|kills=', ''));
		} else if (line.startsWith('|name=')) {
			result.monsterName = line.replace('|name=', '');
		} else {
			const parts = line.slice(1).split(', ');
			if (!parts[1]) console.log(`Missing parts for `, url, line, parts);
			result.items.push({
				itemName: parts[0].replaceAll('[[', '').replaceAll(']]', ''),
				timesDropped: Number(parts[1].replace('times:', '')),
			});
		}
	}
	return result;
};

for (const creature of CREATURES) {
	const slug = creature.replaceAll(' ', '_');
	const result = await handleCreature(slug);
	const json = JSON.stringify(result, null, '\t');
	await fs.writeFile(`./data/${slug}.json`, `${json}\n`);
}

// const result = await handleCreature('Barbarian_Brutetamer');
// console.log(result);
